name: roulette_app
description: "ルーレットをつくろう"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0

  # ★ここを下げた：Dart 3.4.3 でも通るように
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

dependencies:
  flutter_svg: ^2.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/icon.PNG
    - assets/splash.PNG
    - assets/7898C408-6A13-4004-80C3-E1BCC6F6D99D.png
    - assets/bubble_speech.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.PNG
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.PNG
  android: true
  ios: true
